name: CheckIp

# on:
#   schedule:
#     - cron: '*/60 * * * *'
on: [push]


permissions:
  contents: write
  pull-requests: write 
  issues: write
  packages: write

jobs:
  autopublish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false 
          token: ${{ secrets.PUBLISH_TOKEN }}

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install
        run: npm install
      
      - name: run to check
        run: npm run start

      - name: detele
        run: rm -f !(get) 
               
      - name: Pushing to production branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          branch: 'update'
          force: true
          amend: true
          repository: 'MrWang6w/airs2'


          
